version: "3"

services:
    nginx:
      image: nginx
      ports:
        - 80:80
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - /www/work5/PHP:/www

    php:
      image: app
      volumes:
        - /www/work5/PHP:/www

    mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: example
      volumes:
        - /www/work5/db:/var/lib/mysql/

